env:
  global:
    - SETUP=stable

matrix:
  fast_finish: true
  include:
#    - os: linux
#      dist: xenial
#      language: php
#      php: 7.1
#      services:
#        - memcached
#        - redis-server
#        - mysql
#    - os: linux
#      dist: xenial
#      language: php
#      php: 7.1
#      env: SETUP=lowest
#      services:
#        - memcached
#        - redis-server
#        - mysql
#    - os: linux
#      dist: xenial
#      language: php
#      php: 7.2
#      services:
#        - memcached
#        - redis-server
#        - mysql
#    - os: linux
#      dist: xenial
#      language: php
#      php: 7.2
#      env: SETUP=lowest
#      services:
#        - memcached
#        - redis-server
#        - mysql
#    - os: linux
#      dist: xenial
#      language: php
#      php: 7.3
#      services:
#        - memcached
#        - redis-server
#        - mysql
#    - os: linux
#      dist: xenial
#      language: php
#      php: 7.3
#      env: SETUP=lowest
#      services:
#        - memcached
#        - redis-server
#        - mysql

#    - os: osx
#      language: php
#      php: 7.1
#    - os: osx
#      language: php
#      php: 7.1
#      env: SETUP=lowest
#    - os: osx
#      language: php
#      php: 7.2
#    - os: osx
#      language: php
#      php: 7.2
#      env: SETUP=lowest
#    - os: osx
#      language: php
#      php: 7.3
#    - os: osx
#      language: php
#      php: 7.3
#      env: SETUP=lowest

    - os: windows
      language: sh
      env:
        - PHP_VERSION=7.1.25
        - PHP_DIR=php71
    - os: windows
      language: sh
      env:
        - PHP_VERSION=7.1.25
        - PHP_DIR=php71
        - SETUP=lowest
    - os: windows
      language: sh
      env:
        - PHP_VERSION=7.2.13
        - PHP_DIR=php72
    - os: windows
      language: sh
      env:
        - PHP_VERSION=7.2.13
        - PHP_DIR=php72
        - SETUP=lowest
    - os: windows
      language: sh
      env:
        - PHP_VERSION=7.3.0
        - PHP_DIR=php73
    - os: windows
      language: sh
      env:
        - PHP_VERSION=7.3.0
        - PHP_DIR=php73
        - SETUP=lowest

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $TRAVIS_OS_NAME = 'windows' ]]; then choco install php --version $PHP_VERSION -y; fi
  - if [[ $TRAVIS_OS_NAME = 'windows' ]]; then export PATH=/c/tools/$PHP_DIR:$PATH; fi
  - if [[ $TRAVIS_OS_NAME = 'windows' ]]; then echo "extension=php_openssl.dll" >> /c/tools/$PHP_DIR/php.ini; fi
#  - if [[ $TRAVIS_OS_NAME = 'windows' ]]; then choco install mysql redis -y --allow-empty-checksums; fi
  - if [[ $TRAVIS_OS_NAME != 'windows' ]]; then phpenv config-rm xdebug.ini || true; fi
  - if [[ $TRAVIS_OS_NAME != 'windows' ]]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $TRAVIS_OS_NAME != 'windows' ]]; then printf "\n" | pecl install -f redis; fi
  - if [[ $TRAVIS_OS_NAME = 'windows' ]]; then wget https://raw.githubusercontent.com/composer/getcomposer.org/d3e09029468023aa4e9dcd165e9b6f43df0a9999/web/installer -O - -q | php --; fi
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE forge;'

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit
